export default {
    name: 'pageBuilder',
    type: 'array',
    title: 'Page Builder',
    description: 'Add components to page from here',
    of: [
        { type: 'heroHomepage' },
        { type: 'heroBrandpage' },
        { type: 'brandsList' },
        { type: 'bigImageWithSmallImagesCarousel' },
        { type: 'informationSection' },
        { type: 'quoteSection' },
        { type: 'videoBanner' },
        { type: 'textBlockSplit' },
        { type: 'textBlock' },
        { type: 'imageWithDescription' },
        { type: 'imageGrid' },
        { type: 'storySection' },
        { type: 'galleryCarousel' },
        { type: 'bigImage' },
        { type: 'productCarousel' },
        { type: 'jobList' },
        { type: 'progressCarousel' },
        { type: 'progressSection' },
        { type: 'newsLayout' },
        { type: 'membersLayout' },
        { type: 'visionValueSustainability' },
        { type: 'articlesRow' },
        { type: 'downloadBlock'},
        { type: 'articleLanding'},
        { type: 'contactUsLanding'},
        { type: 'progressTextBlock'},
        { type: 'iconRow'},
        { type: 'membersCarousel'},

    ]
}
